reggyshicky/simple_shell

_putchar.c

prints character

---

prompt_print.c

printing prompt to the terminal

---

str_len.c

Review the code uploaded and give me feedback

Finding the length of the argument

---

str_cmp.c

comparing two strings

---

Exit_Env.c

Handling exit and environ

---

find_cmdinputs.c

finding the command inputs from the user

---

str_dup.c

Duplicating strings

---

get_env.c

Getting the contents of global variables

---

_gridfree.c

freeing memory of a grid allocated by malloc

---

memfree.c

Freeing dynamically allocated memory

---

_exec.c

creating a child process

---

main.c

our main.c file

---

_putchar.c

my putchar file

---

exit_shell.c

exiting the simple_shell

---

change_dir.c

changing directory

---

inbuilts.c

checking for inbult commands

---

develop_likedlist.c

creating an empty PATH

---

appendnode.c

appending node/adding path variable

---

get_env.c

Searching for environmental variables

---

pathhand.c

handling path

---

error_hand.c

Handling errors

---

con_cat.c
str_compare.c
str_concat.c
str_duplicate.c
str_length.c

string manipulation

---

printprompt.c

prompt printing

---

simple_shell.c

Our main program

---

str_tkn.c

creating tokesn

---

controls.c

Handling control signals

---

_printint.c
tens_point.c

printing an interger
